---
- name: install and start haproxy for development node(s)
  become: true
  block:
    - name: install haproxy
      apt:
        name: haproxy
        state: present
    - name: start haproxy service
      systemd: 
        name: haproxy
        state: started
        enabled: yes
  when:
    - haproxy_exporter_development_node

- name: create haproxy_exporter group
  become: true
  group:
    name: "{{ haproxy_exporter_system_group }}"
    state: "{{ haproxy_exporter_state }}"
    system: true

- name: create haproxy_exporter user
  become: true
  user:
    name: "{{ haproxy_exporter_system_user }}"
    groups: "{{ haproxy_exporter_system_group }}"
    append: true
    createhome: false
    shell: /usr/sbin/nologin
    state: "{{ haproxy_exporter_state }}"
    system: true

- name: ensure tar is installed
  become: true
  package:
    name: tar
    state: present

- name: download and unarchive haproxy_exporter binary
  unarchive:
    src: "https://github.com/prometheus/haproxy_exporter/releases/download/v{{ haproxy_exporter_version }}/haproxy_exporter-{{ haproxy_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
    creates: "/tmp/haproxy_exporter-{{ haproxy_exporter_version }}.linux-amd64/haproxy_exporter"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: propagate haproxy_exporter binary
  become: true
  copy:
    src: "/tmp/haproxy_exporter-{{ haproxy_exporter_version }}.linux-amd64/haproxy_exporter"
    dest: "{{ haproxy_exporter_bin_dir}}/haproxy_exporter"
    mode: 0750
    owner: "{{ haproxy_exporter_system_user }}"
    group: "{{ haproxy_exporter_system_group }}"
    remote_src: yes
  notify: restart haproxy_exporter

- name: copy haproxy_exporter systemd service file
  become: true
  template:
    src: haproxy_exporter.service.j2
    dest: /etc/systemd/system/haproxy_exporter.service
    owner: root
    group: root
    mode: 0644
  # Prevent Ansible from displaying password
  no_log: true
  notify: restart haproxy_exporter

- name: ensure haproxy_exporter is enabled
  become: true
  systemd:
    name: haproxy_exporter
    enabled: "{{ haproxy_exporter_enabled }}"
    state: started
